### ISSUE TITLE
Stop execution of tests after TLE or MLE

### ISSUE THREAD

**Issue by mikaelmello** [pustaczek/icie#8] opened 2019-05-26 20:04 UTC
Self-explanatory

I'm just listing some improvements that I'd like to implement in the near future

**Comment by pustaczek** [comment] 2019-05-26 20:39
Simply stopping is definitely not the good behavior - usually a later test can get a RE which can be debugged in seconds rather than minutes. If the problem is the long wait for results, I was thinking of displaying test outcomes live rather than waiting for all to finish.

**Comment by mikaelmello** [comment] 2019-05-26 20:42
> Simply stopping is definitely not the good behavior

I guess you're right, regarding MLE a simple warning would suffice.

My reasoning for this issue came from having a lot of hanging executions eating up all my CPU, clicking Cancel on the notification didn't seem to really work.

**Comment by pustaczek** [comment] 2019-05-26 20:48
If that's the case, then I think the spawning and executing code should be fixed instead. I will have to look into it, because it shouldn't spawn multiple tests simultaneously.

**Comment by mikaelmello** [comment] 2019-05-26 20:51
If I had to guess, each hanging process came from a different "test run" (Alt+0). My code had an infinite loop and the extension failed to kill it when I clicked on Cancel.

**Comment by pustaczek** [comment] 2019-05-26 20:56
Thanks, that narrows it down pretty tightly!

**Closed** 2019-05-28 10:08 UTC
